### ISSUE TITLE
Game Patch didn't change

### ISSUE THREAD

**Issue by Klefo0** [dfint/df-translation-client#5]
Message in patch launcher:
![Screenshot 2020-09-21 142623](https://user-images.githubusercontent.com/70630854/93741361-79226a00-fc16-11ea-8f27-74ee3840b086.png)
In DF :
![Screenshot 2020-09-21 142731](https://user-images.githubusercontent.com/70630854/93741433-9d7e4680-fc16-11ea-84c5-a7b3f6a6d3a9.png)
Nothing had changed, it still the old execute.

**Comment by Klefo0** [comment]
1. In Path Execute File tab, when I added .po file, the encode not show code table listings. 
2. Did you not added VISCII table?

**Comment by Klefo0** [comment]
Ok, thanks. But you should note it on the Readme.md.

**Comment by Klefo0** [comment]
@insolor I've found that in Python directory not have VISCII encode and encoding so I'm making one. Can you add it to requirements?

**Comment by insolor** [comment]
> And also why you choose utf16 but not utf8?

DF internally converts text into utf16 using cp437 conversion table and then renders it. To add support of different encodings we must patch the conversion table.

**Comment by Klefo0** [comment]
Maybe you should remove VISCII, then make a conversion table for cp1258
I've found a link talking about it: https://learn-tech-tips.blogspot.com/2016/03/how-to-read-tcvn3-character-in-any-process.html

**Comment by insolor** [comment]
@Klefo0 for cp1258 support all marks under and above letters must be separated from letters, and I don't know yet if DF will be able to treat these separated marks properly. I will try to add this encoding in the future, but I do not promise anything.

**Comment by Klefo0** [comment]
I know, but the code page doesn't have all character in Vietnamese. So I think make a conversion table for it is a good idea, than make a code page in your code but it doesn't exist in Python directory

**Comment by insolor** [comment]
> I know, but the code page doesn't have all character in Vietnamese.

Which one, viscii or cp1258?

> So I think make a conversion table for it is a good idea, than make a code page in your code but it doesn't exist in Python directory

There are some cons and pros. On the one hand, viscii is already working, on the other hand, cp1258 support needs some additional effort to not break support of other encodings (cp1251 for cyrillic, in particular). Technically it is possible to support both (viscii and cp1258) encodings, but for now I tend to leave it as it is.

**Comment by Klefo0** [comment]
> Which one, viscii or cp1258?
The cp1258, but the viscii you wrote not working, so i made the encoding as I mention early.

**Comment by insolor** [comment]
viscii support is already fixed.

**Comment by Klefo0** [comment]
Nope
![Screenshot 2020-09-22 204917](https://user-images.githubusercontent.com/70630854/93891007-224f8a00-fd15-11ea-9394-5fcff3a83df9.png)

**Comment by insolor** [comment]
Again: viscii encoding IS working. dfrus patcher not working.

**Comment by Klefo0** [comment]
But i use df 32-bit

**Comment by insolor** [comment]
@Klefo0 

> dfrus doesn't support 64-bit executables **and is broken anyway**,

**Comment by Klefo0** [comment]
> 
> 
> @Klefo0
> 
> > dfrus doesn't support 64-bit executables **and is broken anyway**,

Yes, so i change to df 32bit

**Comment by insolor** [comment]
dfrus is broken by itself, not because of missing viscii support. Even after you changed DF to 32 bit, it is still broken.

**Comment by Klefo0** [comment]
ok i understood
