### ISSUE TITLE
No Transifex login anymore

### ISSUE THREAD

**Issue by Juli199696** [dfint/df-translation-client#56]
Hey ho, the newest Update broke the Login to Transifex. It does not show up anymore in the Client. 
![image](https://user-images.githubusercontent.com/1338037/205124150-46d3512c-e58e-4d18-a615-28247ffa439e.png)

You cant select Transifex anymore.

Thank you in advance.

**Comment by insolor** [comment]
Old Transifex APIs (2.0, 2.5) don't work anymore, and new API wrapper is not implemented yet. See https://github.com/dfint/df-translation-client/issues/13
So direct downloading from tranisfex is removed for now.

You can use downloading from github, the [translations-backup](https://github.com/dfint/translations-backup) repository updates once a day, you can see it by commits: https://github.com/dfint/translations-backup/commits/main

If you need an URGENT update, I can manually trigger update of translations-backup, but it will not be very convenient if you ask often :)

**Comment by Juli199696** [comment]
Well okay. For the time beeing i will stay with the last update to stay with Transifex as i translate daily with a friend togehter. 

I hope you can include that into the new versions soon :) Stay safe and keep digging a hole ^^

**Comment by insolor** [comment]
Related issues
Add transifex api v.3 implementation #13
Drop support of Transifex API 2.* after November 30, 2022 #51
