### ISSUE TITLE
Encoding field doesn't show lists encoding

### ISSUE THREAD

**Issue by Klefo0** [dfint/df-translation-client#6]
In Path Execute File tab, when I added .po file, the encode not show code table listings. 

_Originally posted by @Klefo0 in https://github.com/dfint/df-translation-client/issues/5#issuecomment-695963133_

**Comment by insolor** [comment]
This issue relates to the VISCII encoding. dfrus technically supports this encoding, but it looks like df-translation-client just doesn't aware of it. I'll fix this.
You can still enter it manually in the encoding field.

**Comment by insolor** [comment]
Must be fixed now. Pull changes from this repository and update requirements (`pip install -U -r requirements.txt`)

**Comment by Klefo0** [comment]
Why using pip instead of pip3?
I've tried pip but it didn't work.

**Comment by insolor** [comment]
On windows, if only python3 version is installed, you can use pip instead of pip3. Of course, if pip doesn't work on your system but pip3 works, use pip3.

**Comment by insolor** [comment]
I think we can close this issue?

**Comment by Klefo0** [comment]
Yea
