### ISSUE TITLE
AttributeError: 'WindowsPath' object has no attribute 'is_relative_to'

### ISSUE THREAD

**Issue by GotrekGurnisson** [dfint/df-translation-client#9]
Win 10 Pro.
`pip 21.0.1 from c:\users\User\appdata\local\programs\python\python38-32\lib\site-packages\pip (python 3.8)`

Just start program. Set paths and press search or translate.

E:\NET\__DwarfFotress_translate\translate_client\df-translation-client-develop>python df-translate.pyw
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "E:\NET\__DwarfFotress_translate\translate_client\df-translation-client-develop\frames\frame_translate_external_files.py", line 189, in <lambda>
    ttk.Button(self, text='Translate', command=lambda: self.bt_search(translate=True)).grid(row=5, column=1)
  File "E:\NET\__DwarfFotress_translate\translate_client\df-translation-client-develop\frames\frame_translate_external_files.py", line 108, in bt_search
    if cur_dir.is_dir() and not cur_dir.is_relative_to(f'{base_path}/Lib'):
AttributeError: 'WindowsPath' object has no attribute 'is_relative_to'

error line:
`if cur_dir.is_dir() and not cur_dir.is_relative_to(f'{base_path}/Lib'):`

it was enough to delete ` and not cur_dir.is_relative_to(f'{base_path}/Lib')` for me but I don't think that it is correct fix :-) 

![error](https://user-images.githubusercontent.com/78147516/106371212-18dccb00-6362-11eb-9421-ae9ca13fb89e.PNG)

**Comment by insolor** [comment]
Fixed with [5e55058](https://github.com/dfint/df-translation-client/commit/5e55058d17c74eed47eecd6d037cf60d8ee04184).

I've removed this because this method appeared only in Python 3.9, but I'd prefer to maintain compatibility with older versions, at least from 3.6.
